server:
  # 旧管理画面と並行稼働で確認するためローカル環境ではポート番号は8081を使用する
  port: 8080
  # servlet.session.timeoutに関しては、各ビルド環境サーバーに直配置しているdocker-compose.ymlの環境変数で管理している。
spring:
  main:
    lazy-initialization: ${SPRING_LAZY_INITIALIZATION:true}
  datasource:
    core-master-db:
      url: mysql://127.0.0.1:3306/core-master-db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      add-mappings: false
      chain:
        strategy:
          content:
            enabled: true
  thymeleaf:
    cache: false
  messages:
    basename: messages/messages
    fallback-to-system-locale: false
logging:
  level:
    root: INFO
    org:
      springframework.web: INFO
      springframework.jdbc: INFO
      springframework.jdbc.core: TRACE
  file:
    name: log/application.log
